name: first workflow
on:
  push:
    branches:
        - "main"

jobs:
    first-workflow-job:
      name: first-job
      runs-on: ubuntu-latest
      steps:

        - name: run bash command
          run: ls
          shell: bash

        - name: checkout action
          uses: actions/checkout@v4

        - name: run bash command
          run: ls
          shell: bash

